# use the node base image
FROM node:20

ARG PROJDIR=/proj-dir
ARG WEBAPPDIR=$PROJDIR/webapp
ARG INVESTMENTAPPDIR=$PROJDIR/investmentapp

# set the working directory to $PROJDIR
WORKDIR $PROJDIR

# copy the current directory contents into the container
ADD ./webapp/requirements-dev.txt $WEBAPPDIR/requirements-dev.txt
ADD ./investmentapp/requirements-dev.txt $INVESTMENTAPPDIR/requirements-dev.txt
ADD ./webapp/client/package.json $WEBAPPDIR/client/package.json

# hack to jump over PEP668
ENV PIP_BREAK_SYSTEM_PACKAGES=1

# install apt-get dependencies
RUN apt-get update -y
RUN apt-get -y install python3 python3-dev python3-pip cron libffi-dev cmake

# install pip and its dependencies
RUN pip install --upgrade pip setuptools wheel

# install test dependencies
RUN pip install -r $WEBAPPDIR/requirements-dev.txt
RUN pip install -r $INVESTMENTAPPDIR/requirements-dev.txt

# install npm and npm dependencies
RUN npm install -g npm@10.5.2
